name: aoc_2015
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/RhubarbXXIII/AdventOfCode

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.19.1
  convert: ^3.1.2
  crypto: ^3.0.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
